### ISSUE TITLE
你好，有没有插入的图片的点击事件啊？？

### ISSUE THREAD

**Issue by liguangze** [tpnet/SpanTextView#1]
有没有插入的图片的点击事件啊

**Comment by tpnet** [comment]
@liguangze  正在编写，今天估计完成

**Comment by liguangze** [comment]
@tpnet  你的demo 是用文字替换图片了，能不能我点击一个图片，然后更换成另一个图片

**Comment by tpnet** [comment]
@liguangze  可以了，已经更新，在demo里面，你点击 "最后面添加图片"后面的图片就可以替换了，增加了一个replaceImageSpan方法

**Comment by liguangze** [comment]
@tpnet  好的，谢谢，我去试一下

**Comment by ruanbaojun1105** [comment]
six
